package com.coppel.sanatudeudaapp.modelos

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table ABONOS.
 */
data class Abonos (var idu_abono: Int? = null,
                   var idu_negociacion: Int? = null,
                   var atrasado: Boolean? = null,
                   var fecha_hora: String? = null,
                   var folio: String? = null,
                   var monto: Int? = null,
                   var tienda: String? = null) {

    constructor():this(
            0,
            0,
            false,
            "",
            "",
            0,
            "")

}
