package com.coppel.sanatudeudaapp.modelos

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table NEGOCIACION.
 */
data class Negociacion (var idu_negociacion: Int?,
                        var idu_cliente: Int?,
                        var idu_producto: Int?,
                        var saldo_anterior: Int?,
                        var atrasado: Int?,
                        var moratorio: Int?,
                        var dia_formalizacion: String?,
                        var plazo: Int?){

    constructor():this(
            0,
            0,
            0,
            0,
            0,
            0,
            "",
            0)

}
